In [3]:
import numpy as np

In [17]:
np.seterr(divide='ignore')
p = np.arange(4,8)
q = np.arange(0,4)
elemented_wise = p+q
dif = p-q
division = p/q
squared = p**q
mult = p*10
print(f"{elemented_wise}\n {dif}\n {division}\n {squared}\n {mult}")

[ 4  6  8 10]
 [4 4 4 4]
 [       inf 5.         3.         2.33333333]
 [  1   5  36 343]
 [40 50 60 70]


In [21]:
arr = np.arange(1,11)
squ = arr**2
print(squ)

[  1   4   9  16  25  36  49  64  81 100]


In [26]:
vec = np.arange(1,21)
vec[vec % 2 != 0] =0
print(vec)

[ 0  2  0  4  0  6  0  8  0 10  0 12  0 14  0 16  0 18  0 20]


In [27]:
vec = np.arange(1,21)
vec[vec % 2 ==0 ]= 0
print(vec)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


In [32]:
arr = np.arange(1, 21)
squ = 2 ** arr
print(squ)

[      2       4       8      16      32      64     128     256     512
    1024    2048    4096    8192   16384   32768   65536  131072  262144
  524288 1048576]


In [33]:
arr = np.arange(0,5)
res = 10 ** arr
print(res)

[    1    10   100  1000 10000]


In [41]:
arr = np.arange(1,51)
res = sum(1/(arr*(arr+1)))
print(f"{res:.7f}")

0.9803922


In [42]:
arr = np.arange(0, 21)
squ = np.sum(1/(2 ** arr))
print(f"{squ:.6f}")

1.999999


In [59]:
arr = np.arange(1,29,3)
n = np.arange(0,10)
squ = 3**n
res = np.sum(arr/squ)
print(f"{res:.6f}")

3.749174


In [65]:
arr = np.arange(1,29,3)
n = np.arange(0,10)
squ = 3**n
res = arr/squ
mask_great = res > 0.5
count = np.sum(mask_great)
print(f"{count}")

3
