In [1]:
import numpy as np

In [7]:
m1 =np.ones((4,4))
m1[1:3, 1:3] = 2
print(m1)
print(f"2 и 3 столбцы матрицы\n {m1[:, 1:3]}")


[[1. 1. 1. 1.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [1. 1. 1. 1.]]
2 и 3 столбцы матрицы
 [[1. 1.]
 [2. 2.]
 [2. 2.]
 [1. 1.]]
