In [2]:
import numpy as np

In [9]:
m1 =np.ones((4,4))
print(m1, "\n")
m1[1:3, 1:3] = 2
print(m1)
print(f"2 и 3 столбцы матрицы\n {m1[:, 1:3]}\n")

row_vec = m1[1, :]
col_vec = m1[:, 1]
print (row_vec == col_vec)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 1. 1. 1.]
 [1. 2. 2. 1.]
 [1. 2. 2. 1.]
 [1. 1. 1. 1.]]
2 и 3 столбцы матрицы
 [[1. 1.]
 [2. 2.]
 [2. 2.]
 [1. 1.]]

[ True  True  True  True]


In [19]:
m2 = np.arange(1,31).reshape((5,6), order="F")
m2_del = np.delete(m2,2,axis=0)
m2_del = np.delete(m2_del, 1, axis=1)
m2_multiplication = m2_del*100
m2_squ = m2**2
m2_squ_minus = m2_squ - m2
print(f"{m2}\n\n {m2_del}\n\n {m2_multiplication}\n\n {m2_squ}\n\n {m2_squ_minus}")

[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]

 [[ 1 11 16 21 26]
 [ 2 12 17 22 27]
 [ 4 14 19 24 29]
 [ 5 15 20 25 30]]

 [[ 100 1100 1600 2100 2600]
 [ 200 1200 1700 2200 2700]
 [ 400 1400 1900 2400 2900]
 [ 500 1500 2000 2500 3000]]

 [[  1  36 121 256 441 676]
 [  4  49 144 289 484 729]
 [  9  64 169 324 529 784]
 [ 16  81 196 361 576 841]
 [ 25 100 225 400 625 900]]

 [[  0  30 110 240 420 650]
 [  2  42 132 272 462 702]
 [  6  56 156 306 506 756]
 [ 12  72 182 342 552 812]
 [ 20  90 210 380 600 870]]


In [38]:
col = np.arange(1,10).reshape(9,1)
row = np.arange(1,10)
multi_table = col*row
sub_matrix = multi_table[5:8, 2:7]
bool_matrix = np.where(multi_table >= 10, True, False)
multi_table2 = np.where(multi_table <10, 0, multi_table)
print(f"{multi_table}\n\n {sub_matrix}\n\n {bool_matrix}\n\n {multi_table2}")

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]

 [[18 24 30 36 42]
 [21 28 35 42 49]
 [24 32 40 48 56]]

 [[False False False False False False False False False]
 [False False False False  True  True  True  True  True]
 [False False False  True  True  True  True  True  True]
 [False False  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]
 [False  True  True  True  True  True  True  True  True]]

 [[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10 12 14 16 18]
 [ 0  0  0 12 15 18 21 24 27]
 [ 0  0 12 16 20 24 28 32 36]
 [ 0 10 15 20 25 30 35 40 45]
 [ 0