In [1]:
import numpy as np
import string

In [ ]:
alphabet_list = list(string.ascii_lowercase)
num_array = np.arange(1,6)
list1 = {
    'numbers' : num_array,
    'letters' : alphabet_list,
    'logic' : True

}
# Имитация R-команды ist[1]
# Создаем новый словарь, забирая ключ  и его содержимое
sliced_list_numbers = {'numbers': list1['numbers']}
sliced_list_numbers2 = list(list1.values())[0]
print(f"{list1}\n {sliced_list_numbers['numbers']}\n {sliced_list_numbers2}\n {list1['numbers'][0]}")

{'numbers': array([1, 2, 3, 4, 5]), 'letters': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'], 'logic': True}
 [1 2 3 4 5]
 [1 2 3 4 5]
 1



In [24]:
list2 ={
    'pupa' : list1,
    "lupa" : list1
}
print(f" {list2['pupa']['numbers']}\n {list2['pupa']['letters']}\n {list2['pupa']['logic']}\n")
print(f" {list2['lupa']['numbers']}\n {list2['lupa']['letters']}\n {list2['lupa']['logic']}\n")
deep_value = list2['pupa']['letters'][2]
print(deep_value)

 [1 2 3 4 5]
 ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
 True

 [1 2 3 4 5]
 ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
 True

c
