In [1]:
import numpy as np

def get_element(arr,index,default = "N/A"):
    try:
        return arr[index]
    except IndexError:
        return default


In [22]:
arr = np.arange(3,28,3)
print(arr[1], arr[4], arr[6])
print("Предпоследний элемент", arr[-2])
print("Все кроме последнего", arr[:-1])

6 15 21
Предпоследний элемент 24
Все кроме последнего [ 3  6  9 12 15 18 21 24]


In [51]:
vec3 = np.array([3, 5, 2, 1, 8, 4, 9, 10, 3, 15, 1, 11])
print(f"второй элемент {vec3[1]}")
print(f"второй и пятый элемент в {vec3[[1,4]]}")
print(f"сотое значение вектора {get_element(vec3, 99)}")
print(f"все элементы кроме второго элемента {np.delete(vec3, 1)}")
print(f"все элементы кроме второго и пятого элемента {np.delete(vec3, [1,4])}")
print(f"последний элемент вектора {vec3[-1]}")
print(f"все значения кроме первого и последнего {np.delete(vec3, [0,-1])}")
print(f"все значения, которые больше 4 {vec3[vec3 > 4]}")
print(f"все значения, которые больше 4, но меньше 10 {vec3[(vec3 > 4) & (vec3<10)]}")
print(f"все значения, которые больше 4 {vec3**2}")

второй элемент 5
второй и пятый элемент в [5 8]
сотое значение вектора N/A
все элементы кроме второго элемента [ 3  2  1  8  4  9 10  3 15  1 11]
все элементы кроме второго и пятого элемента [ 3  2  1  4  9 10  3 15  1 11]
последний элемент вектора 11
все значения кроме первого и последнего [ 5  2  1  8  4  9 10  3 15  1]
все значения, которые больше 4 [ 5  8  9 10 15 11]
все значения, которые больше 4, но меньше 10 [5 8 9]
все значения, которые больше 4 [  9  25   4   1  64  16  81 100   9 225   1 121]


In [ ]:
sp1 = np.arange(2,21,2)
arr = np.arange(1,21)
sp2 = arr[arr % 2 == 0]
sp3 = arr[1::2]
arr2 = np.arange(1,11)
sp4= 2* arr2
print(f"{sp1}\n{sp2}\n{sp3}\n{sp4}")

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#Lab6
vec4 = np.array([300, 15, 8, 20, 0, 1, 110], dtype=float)
vec4[vec4>20] = np.nan
sum_vect = np.nansum(vec4)
print(vec4)
print(sum_vect)

[nan 15.  8. 20.  0.  1. nan]
44.0
