In [24]:
import numpy as np
import math

In [2]:
vec = np.array([2,30,40])
print(vec)

[ 2 30 40]


In [4]:
vec = np.arange(1,21,1)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
vec = np.arange(20,0,-1)
print(vec)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [11]:
vec = np.arange(1,101,1)
sum_vec =np.sum(vec)
print(sum_vec)

5050


In [13]:
part1 = np.arange(1,21,1)
part2 = np.arange(19,0,-1)
result = np.concatenate([part1,part2])
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 19 18 17 16
 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [14]:
part1 = np.arange(5,1,-1)
part2 = np.arange(2,6,1)
res = np.concatenate([part1, part2])
print(res)

[5 4 3 2 2 3 4 5]


In [15]:
vect = np.arange(2,21,2)
print(vect)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
np.set_printoptions(formatter={'float': '{:0.1f}'.format})
vect = np.arange(0.1,1.1,0.1)
print(vect)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0]


In [21]:
year_vec =np.arange(2020,2101,4)
print(year_vec)

[2020 2024 2028 2032 2036 2040 2044 2048 2052 2056 2060 2064 2068 2072
 2076 2080 2084 2088 2092 2096 2100]


In [23]:
hey_vec=np.repeat("Хэй!", 20)
print(hey_vec)

['Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!'
 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!' 'Хэй!']


In [34]:
np.set_printoptions(formatter=None)
vec = np.arange(1,11)
roots = np.sqrt(vec)
print(roots)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [35]:
res = np.repeat(np.arange(1,10), np.arange(1,10))
print(res)

[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 9
 9 9 9 9 9 9 9 9]
